name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for VS Marketplace validation
        run: sleep 5m
        shell: bash
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          release_text: "[Download](https://marketplace.visualstudio.com/items?itemName=object-Object.hex-casting) | [Changelog](https://github.com/object-Object/vscode-hex-casting/blob/main/CHANGELOG.md)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
